// <auto-generated />
namespace InfoTrucker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _14001027 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14001027));
        
        string IMigrationMetadata.Id
        {
            get { return "202201170836409_14001027"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
