//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTrucker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoTrucker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_user_male_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-add-user-male-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_data_backup_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-data-backup-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_database_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-database-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_database_restore_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-database-restore-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_message_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-message-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_new_message_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-new-message-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_subscription_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-subscription-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use 95 insert into ApplicationUsers (UserId ,Editor,Enabled,FullName,LimetedCompany,UserName,UserPassword) 
        ///Values (1,&apos;Admin&apos;,1,&apos;مدیرسیستم&apos;,0,&apos;o2DUeeUN//chNK6u9APQdw==&apos;,&apos;r1iuHVzwh0BHzDa+rauWxg==&apos;).
        /// </summary>
        internal static string ScriptApplicationUser {
            get {
                return ResourceManager.GetString("ScriptApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use 95
        ///
        ///insert into MenuGroups (MenuGroupTitle,Description) Values(&apos;DocumentRibbonPage&apos;,&apos;اسناد&apos;)
        ///insert into MenuGroups (MenuGroupTitle,Description) Values(&apos;ReportRibbonPage&apos;,&apos;گزارشات&apos;)
        ///insert into MenuGroups (MenuGroupTitle,Description) Values(&apos;SmsRibbonPage&apos;,&apos;سامانه پیام کوتاه&apos;)
        ///insert into MenuGroups (MenuGroupTitle,Description) Values(&apos;ManageRibbonPage&apos;,&apos;مدیریت نرم افزار&apos;)
        ///
        ///insert into MenuItems (GroupID_FK,ItemTitel,Description) Values (1,&apos;PersonPageGroup&apos;,&apos;رانندگان انجمن&apos;)
        ///insert into MenuItem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptMenu {
            get {
                return ResourceManager.GetString("ScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Database [95]    Script Date: 1/18/2022 8:36:02 AM ******/
        ///CREATE DATABASE [95]
        /// CONTAINMENT = NONE
        /// ON  PRIMARY 
        ///( NAME = N&apos;95&apos;, FILENAME = N&apos;AddressFileForSave\95.mdf&apos; , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
        /// LOG ON 
        ///( NAME = N&apos;95_log&apos;, FILENAME = N&apos;AddressFileForSave\95_log.ldf&apos; , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
        ///GO
        ///ALTER DATABASE [95] SET COMPATIBILITY_LEVEL = 140
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlScriptForNewDatabase {
            get {
                return ResourceManager.GetString("sqlScriptForNewDatabase", resourceCulture);
            }
        }
    }
}
